import type { FeedGroup } from '~/types/feed'
import { getGhAvatar } from './utils/img'

export default [{
    name: '相谈甚多',
    desc: '',
    entries: [{
            author: '冬烟 の 小窝',
            sitenick: '冬烟',
            title: '冬烟 の 小窝',
            desc: '你猜，我猜你肯定猜不到嘿嘿……',
            link: 'https://blog.45m.fun/',
            feed: 'https://blog.45m.fun/',
            icon: 'https://q.qlogo.cn/g?b=qq&nk=3010013479&s=640',
            avatar: 'https://q.qlogo.cn/g?b=qq&nk=3010013479&s=640',
            archs: ['Nuxt', 'Vercel'],
            date: '2020-01-29',
            comment: '技术好友,喜欢各种折腾',
        },{
            author: '玄枵',
            sitenick: '神殇',
            title: '玄枵',
            desc: '欲买桂花重载酒，终不似，少年游',
            link: 'https://blog.shenshang.online',
            feed: 'https://blog.shenshang.online',
            icon: 'https://lsky.shenshang.online/ROIyVx.png',
            avatar: 'https://lsky.shenshang.online/ROIyVx.png',
            archs: ['Halo', '服务器'],
            date: '2025-06-07',
            comment: '技术好友,喜欢各种折腾',
        },{
            author: 'ZZblackingの小博客',
            sitenick: 'ZZblacking',
            title: 'ZZblackingの小博客',
            desc: '最是人间留不住，朱颜辞镜花辞树',
            link: 'https://blog.zzblacking.fun/',
            feed: 'https://blog.zzblacking.fun/',
            icon: 'https://blog.zzblacking.fun/upload/illust_131115035_20250604_025748.png',
            avatar: 'https://blog.zzblacking.fun/upload/illust_131115035_20250604_025748.png',
            archs: ['Halo', '服务器'],
            date: '2025-06-07',
            comment: '技术好友,喜欢各种折腾',
        },{
            author: '未雨屏の博客',
            sitenick: 'Dr.未雨屏',
            title: '未雨屏の博客',
            desc: '我曾经也是一个懵懂的孩子··········',
            link: 'https://weiyuping.top/',
            feed: 'https://weiyuping.top/',
            icon: 'https://avatars.githubusercontent.com/u/91879812?v=4',
            avatar: 'https://avatars.githubusercontent.com/u/91879812?v=4',
            archs: ['Hexo', '服务器'],
            date: '2025-06-09 ',
            comment: 'MC开服圈',
    ],
}] satisfies FeedGroup[]
